import { ACTION_NAME } from '../../constants/ACTION_NAME';
import { ACTION_STATUS } from '../../constants/ACTION_STATUS';
import { ActionType } from '../../types.d';

const compose = (action: string): ActionType => {
  return {
    IN_PROGRESS: `${ACTION_STATUS.IN_PROGRESS}@${action}`,
    SUCCESS: `${ACTION_STATUS.SUCCESS}@${action}`,
    FAILURE: `${ACTION_STATUS.FAILURE}@${action}`,
  };
};

const SIGNUP_USER = compose(ACTION_NAME.SIGNUP_USER);
const SIGNIN_USER = compose(ACTION_NAME.SIGNIN_USER);
const KEEP_AUTH_USER = compose(ACTION_NAME.KEEP_AUTH_USER);
const SIGNOUT_USER = compose(ACTION_NAME.SIGNOUT_USER);

const GET_MY_STORE = compose(ACTION_NAME.GET_MY_STORE);
const CREATE_STORE = compose(ACTION_NAME.CREATE_STORE);
const UPDATE_STORE = compose(ACTION_NAME.UPDATE_STORE);
const UPDATE_STORE_LOGO = compose(ACTION_NAME.UPDATE_STORE_LOGO);

const CREATE_SALE_MANAGER = compose(ACTION_NAME.CREATE_SALE_MANAGER);
const UPDATE_SALE_MANAGER = compose(ACTION_NAME.UPDATE_SALE_MANAGER);
const DELETE_SALE_MANAGER = compose(ACTION_NAME.DELETE_SALE_MANAGER);
const READ_SALE_MANAGERS = compose(ACTION_NAME.READ_SALE_MANAGERS);
const BLOCK_SALE_MANAGER = compose(ACTION_NAME.BLOCK_SALE_MANAGER);

export {
  BLOCK_SALE_MANAGER,
  CREATE_SALE_MANAGER,
  CREATE_STORE,
  DELETE_SALE_MANAGER,
  GET_MY_STORE,
  KEEP_AUTH_USER,
  READ_SALE_MANAGERS,
  SIGNIN_USER,
  SIGNOUT_USER,
  SIGNUP_USER,
  UPDATE_SALE_MANAGER,
  UPDATE_STORE,
  UPDATE_STORE_LOGO,
};
