export const ACTION_NAME = {
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNOUT_USER: 'SIGNOUT_USER',
  KEEP_AUTH_USER: 'KEEP_AUTH_USER',
  GET_MY_STORE: 'GET_MY_STORE',
  CREATE_STORE: 'CREATE_STORE',
  UPDATE_STORE: 'UPDATE_STORE',
  UPDATE_STORE_LOGO: 'UPDATE_STORE_LOGO',
};
